import{a as v,S as E,i as u}from"./assets/vendor-D5mnuR-h.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const h of a.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&r(h)}).observe(document,{childList:!0,subtree:!0});function o(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(s){if(s.ep)return;s.ep=!0;const a=o(s);fetch(s.href,a)}})();v.defaults.baseURL="https://pixabay.com/api/";const d={key:"49331569-d75c2214014d7ff2c794993e6",image_type:"photo",orientation:"horizontal",safesearch:!0};function L(t,e=1,o=15){return d.q=t,d.page=e,d.per_page=o,v.get("",{params:d})}function b(t,e){const o=[];t.forEach(r=>{o.push(`<li>
                <a class="gallery-link" href="${r.largeImageURL}">
                    <img src="${r.previewURL}" alt="${r.tags}">
                    <ul>
                        <li>
                            <p>Likes: <span>${r.likes}</span></p>
                        </li>
                        <li>
                            <p>Views: <span>${r.views}</span></p>
                        </li>
                        <li>
                            <p>Comments: <span>${r.comments}</span></p>
                        </li>
                        <li>
                            <p>Downloads: <span>${r.downloads}</span></p>
                        </li>
                    </ul>
                </a>
            </li>`)}),e.gallery.insertAdjacentHTML("beforeend",o.join("")),e.lightbox.refresh(),e.isPaging&&x(e.gallery.querySelector(".gallery-link").getBoundingClientRect().height*2)}function x(t){window.scrollBy({top:t,left:0,behavior:"smooth"})}function k(t){t.innerHTML=""}const p=document.querySelector('input[name="search-text"]'),q=document.querySelector('button[type="submit"]'),w=document.querySelector(".gallery"),l=document.querySelector(".loading"),n=document.querySelector(".load-more-button"),f=document.querySelector(".end-of-search"),C=document.querySelector(".back-to-top"),D={theme:"dark",backgroundColor:"#EF4040",position:"topRight",messageColor:"#FAFAFB",message:"Please enter search terms",iconUrl:"./error-alert.svg",iconColor:"white",messageSize:"16px",messageLineHeight:"24px",progressBarColor:"#B51B1B"},F={theme:"dark",backgroundColor:"#EF4040",position:"topRight",messageColor:"#FAFAFB",message:"No images found, try again",iconUrl:"./error-alert.svg",iconColor:"white",messageSize:"16px",messageLineHeight:"24px",progressBarColor:"#B51B1B"},O={captionsData:"alt",captionDelay:250},T=new E(".gallery a",{...O}),g={gallery:w,lightbox:T,isPaging:!1};let c=1;const m=15;let S,i=p.value,y;function H(t){S=Math.floor(t/m)}function P(){c++}function M(){c=1}function B(){return S<c}q.addEventListener("click",async t=>{if(t.preventDefault(),k(w),M(),f.classList.add("visually-hidden"),n.classList.add("visually-hidden"),!i||i===""){u.show({...D});return}l.classList.remove("visually-hidden"),await L(i,c,m).then(e=>{l.classList.add("visually-hidden"),e.data.totalHits>0?(g.isPaging=!1,b(e.data.hits,g),H(e.data.totalHits),B()?f.classList.remove("visually-hidden"):(g.isPaging=!0,P(),n.classList.remove("visually-hidden"),y=i)):u.show({...F})}).catch(e=>{l.classList.add("visually-hidden"),console.error("Error:",e),u.error({title:"Error",message:"Error fetching results, try again later (check console for details)"})})});n.addEventListener("click",async t=>{t.preventDefault(),n.classList.add("visually-hidden"),await L(y,c,m).then(e=>{l.classList.add("visually-hidden"),e.data.totalHits>0&&(b(e.data.hits,g),B()?(n.classList.add("visually-hidden"),f.classList.remove("visually-hidden")):(P(),y=i))}).catch(e=>{l.classList.add("visually-hidden"),console.error("Error:",e),u.error({title:"Error",message:"Error fetching results, try again later (check console for details)"})})});C.addEventListener("click",t=>{t.preventDefault(),window.scrollTo(0,0)});p.addEventListener("input",()=>i=p.value.trim());
//# sourceMappingURL=index.js.map
